apiVersion: v1
kind: Secret
metadata:
  name: chat-db-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Y2hhdHBhc3N3b3Jk
  MYSQL_USER: Y2hhdHVzZXIK
  MYSQL_PASSWORD: Y2hhdHBhc3N3b3JkCg==
  MYSQL_DATABASE: Y2hhdAo=
