apiVersion: v1
kind: Secret
metadata:
  name: chat-db-secret
  namespace: default
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk # base64 encoded 'rootpassword'
  mysql-user: Y2hhdHVzZXI= # base64 encoded 'chatuser'
  mysql-password: Y2hhdHBhc3N3b3Jk # base64 encoded 'chatpassword'
  mysql-database: Y2hhdA== # base64 encoded 'chat'