DROP DATABASE chat;
CREATE DATABASE IF NOT EXISTS chat;

USE chat;
DROP TABLE IF EXISTS messages;
CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    message TEXT NOT NULL,
    timestamp DATETIME,
    type VARCHAR(50)
);


CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'chatpassword';
ALTER USER 'root'@'%' IDENTIFIED BY 'chatpassword';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;


CREATE USER IF NOT EXISTS 'chatuser'@'%' IDENTIFIED BY 'chatpassword';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'chatpassword';

GRANT ALL PRIVILEGES ON chat.* TO 'chatuser'@'%';


FLUSH PRIVILEGES;
