apiVersion: v1
kind: Service
metadata:
  name: ai-app
  labels:
    app: ai-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 100
    targetPort: 100
    nodePort: 30091
  selector:
    app: ai-app
    tier: frontend
