apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat
      tier: backend
  template:
    metadata:
      labels:
        app: chat
        tier: backend
    spec:
      containers:
      - name: chat-backend
        image: localhost:5000/chat-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://chat-db-service:3306/chat"
        - name: DB_USER
          value: "chatuser"
        - name: DB_PASSWORD
          value: "chatpassword"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"