apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cms-data" # Use a directory that persists in Kind
